ADD: Team Card Component
E-cell-NITS/Srijan-2023 pull request #11
Opened 2023-02-24 19:58 UTC by BIPS8812

#8

2023-02-25 10:40 UTC, codadept requested changes

2023-02-25 10:40 UTC, codadept commented on src/Components/TeamCard/TeamCard.jsx
> +            href="https://www.facebook.com/ronny.kumar.7186896"
add target="_blank" to all the <a> tags to open the link in a new tab

2023-02-25 10:40 UTC, codadept commented on src/Components/TeamCard/TeamCard.module.scss
> +@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@500;700&display=swap");
Poppins is already imported in the index.scss page just use as

```css
font-family: var(--srijan4-font-1);
```

2023-02-25 10:45 UTC, codadept commented
According to me there should be a bit of box shadow on the team card to show that it can be hovered. Just have a talk with Maharnav and figure it out?

2023-02-25 11:01 UTC, JOSU9435 requested changes

2023-02-25 11:01 UTC, JOSU9435 commented on src/Components/TeamCard/TeamCard.jsx
> +      </div>
pass props down the component for the image

2023-02-25 11:01 UTC, JOSU9435 commented on src/Components/TeamCard/TeamCard.jsx
> +          >
- pass props down the component for social links
- open social links in a new tab using `taget="_blank"` and `rel="noreferrer"`

2023-02-25 11:01 UTC, JOSU9435 commented on src/Components/TeamCard/TeamCard.jsx
> +        <div className={style.memberDesignation}>Developer</div>
pass props down the component for name and position

2023-02-25 11:01 UTC, JOSU9435 commented on src/Components/TeamCard/TeamCard.module.scss
> +      box-shadow: 0px 4px 100px rgba(6, 0, 0, 0.66);
refrain from using pixels instead use relative units

2023-02-25 11:01 UTC, JOSU9435 commented on src/Components/TeamCard/TeamCard.module.scss
> +    background: linear-gradient(180deg, #cd6880 28.13%, rgba(9, 145, 222, 0.38) 100%);
use CSS variables for gradients, colors, etc.

2023-02-25 11:01 UTC, JOSU9435 commented on src/Components/TeamCard/TeamCard.module.scss
> +      color: #ffffff;
use CSS variables for gradients, colors etc.

2023-02-25 11:01 UTC, JOSU9435 commented on src/Components/TeamCard/TeamCard.module.scss
> +        color: #fff;
use CSS variables for gradients, colors etc.

2023-02-25 18:49 UTC, codadept commented
Instead of using @iconify use react-icons, as it is used by others

2023-02-26 09:15 UTC, codadept approved these changes

2023-02-26 09:18 UTC, merged