ADD: react toastify
E-cell-NITS/Srijan-2023 pull request #37
Opened 2023-03-04 18:19 UTC by AnubhavChakrabortynits

react toastify added

backend api testing done...

2023-03-04 19:48 UTC, codadept approved these changes

2023-03-04 19:48 UTC, codadept commented on package.json
> +    "dotenv": "^16.0.3",
Why have you installed dotenv? 

To use environment variables in vite [see this](https://vitejs.dev/guide/env-and-mode.html)

2023-03-04 19:49 UTC, codadept requested changes
Make the requested changes

2023-03-05 10:20 UTC, AnubhavChakrabortynits commented
removed dotenv

2023-03-05 18:10 UTC, codadept approved these changes

2023-03-05 18:10 UTC, merged