ADD: New event card
E-cell-NITS/Srijan-2023 pull request #38
Opened 2023-03-05 15:40 UTC by kherkatary

### ADD: 
New Event Card component

#### Card structure
- size : small | large
- card content to be passed as props

2023-03-05 18:13 UTC, codadept approved these changes

2023-03-05 18:15 UTC, codadept commented
![image](https://user-images.githubusercontent.com/63517465/222978108-b924ec3c-35c6-499a-8d7e-e129f624fa03.png)

- Increase the font size of register and details buttons a bit.,

- Also if the old EventCard Component won't be used again then delete that component and rename the NewCard Component to EventCard Component

2023-03-05 18:15 UTC, codadept requested changes
Checkout the comment for requested changes

2023-03-05 18:16 UTC, codadept commented
Also properly display the Event Card component in the Home Page

2023-03-06 06:20 UTC, JOSU9435 requested changes
![image](https://user-images.githubusercontent.com/77873211/223030417-a39462c8-27e7-4f19-a560-99b5c9a359c0.png)

- proportionally decrease the border radius of the smaller card with respect to the large one
- reduce the size of the title a bit such that it fits in one line
- properly implement ellipses on content overflow
- refrain from using px as units replace all the px units in CSS files with relative units like rem, %, vh ...
-

2023-03-06 06:20 UTC, JOSU9435 commented on src/Pages/Home/Home.jsx
> +
display cards using **map** function

2023-03-06 06:20 UTC, JOSU9435 commented on src/Components/EventCard/Large.module.scss
> +        font-size: 4vmin;
rem unit would be more appropriate for font sizes

2023-04-05 15:43 UTC, JOSU9435 requested changes

2023-04-05 15:43 UTC, JOSU9435 commented on src/Components/EventCard/EventCard.jsx
> +                <button className={styles.details}>Details</button>
replace  `<button>` tag to `<Link>` tag

2023-04-05 15:43 UTC, JOSU9435 commented on src/Components/EventCard/Large.module.scss
replace px unit with equivalent relative unit

2023-04-05 15:43 UTC, JOSU9435 commented on src/Components/EventCard/Small.module.scss
replace px unit with equivalent relative unit

2023-04-06 04:47 UTC, JOSU9435 approved these changes

2023-04-06 04:48 UTC, JOSU9435 approved these changes

2023-04-06 18:37 UTC, merged